import Head from "next/head";
import Featured from "../src/components/Featured";
import PizzaList from "../src/components/PizzaList";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Minut Dva Dostava</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Featured />
      <PizzaList />
    </div>
  );
}
